networks:
  csg-network:
    name: csg-network

volumes:
  static-vol:
    name: static-vol

x-common-attrs: &common-attrs
  env_file: .env
  networks:
    - csg-network
  volumes:
    - static-vol:/csg/build

services:
  csg-be:
    << : *common-attrs
    build: backend
    image: csg-be:latest
    container_name: csg-be
    ports:
      - 5075:5075
    develop:
      watch:
        - action: sync
          path: ./
          target: /csg
  csg-fe-dev:
    << : *common-attrs
    build: frontend
    image: csg-fe:latest
    container_name: csg-fe-dev
    ports:
      - 3075:3075
