networks:
  csg-network:
    name: csg-network

volumes:
  static-vol:
    name: static-vol

x-common-attrs: &common-attrs
  env_file: .env
  networks:
    - csg-network

services:
  csg-be:
    << : *common-attrs
    build: backend
    image: csg-be:latest
    container_name: csg-be
    ports:
      - 5075:5075
    volumes:
      - ./backend:/backend
      - ./wsgi.py:/wsgi.py
      - static-vol:/backend/build
  csg-fe-dev:
    << : *common-attrs
    build: frontend
    image: csg-fe:latest
    container_name: csg-fe-dev
    ports:
      - 3075:3075
      - 6006:6006
    command: ["pnpm", "start"]
    volumes:
      - ./frontend:/csg
      - static-vol:/csg/build
  csg-nginx:
    << : *common-attrs
    image: nginx:latest
    container_name: csg-nginx
    ports:
      - 8080:80
    volumes:
      - static-vol:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - csg-be
      - csg-fe-dev
