networks:
  csg-network:
    name: csg-network

volumes:
  static-vol:
    name: static-vol

x-common-attrs: &common-attrs
  env_file: .env
  networks:
    - csg-network
  volumes:
    - static-vol:/backend/build

services:
  csg-backend:
    << : *common-attrs
    build: backend
    image: csg-backend:latest
    container_name: csg-backend
    ports:
      - 5075:5075
    volumes:
      - ./backend:/backend
  csg-fe-dev:
    << : *common-attrs
    build: frontend
    image: csg-fe:latest
    container_name: csg-fe-dev
    ports:
      - 3075:3075
      - 6006:6006
    command: ["pnpm", "start"]
    volumes:
      - ./frontend:/csg
